pageinfo = [[1276876607,8041],
	[1276877377,14451],
	[1276877423,7422],
	[1276877433,9012],
	[1276877457,8676],
	[1276877455,9860],
	[1276877407,9504],
	[1276877375,23844],
	[1276877405,9249],
	[1276876969,23259],
	[1276875801,19253],
	[1276893895,14033],
	[1276877401,11042],
	[1276893875,12070],
	[1276877415,7665],
	[1276894325,9183],
	[1276877449,7461],
	[1276893869,23408],
	[1276877453,11817],
	[1276877373,29518],
	[1276877391,17194],
	[1276877385,8044],
	[1276893761,8927],
	[1276893943,8484],
	[1276877387,30419],
	[1276877419,8648],
	[1276877461,7817],
	[1276893357,10851],
	[1276893765,9394],
	[1276877409,8540],
	[1276877381,12787],
	[1276893857,45893],
	[1276877395,13656],
	[1276877397,11510],
	[1276877427,11191],
	[1276893899,13173],
	[1276877417,6988],
	[1276877429,7877],
	[1276877411,7122],
	[1276877263,90986],
	[1276877435,7938]];
pagedata = [ ["./acknowledgements.htm","Acknowledgements","﻿Acknowledgements The Fractal Flame algorithm was originally written by Scott Draves in 1992. A component from his flame software suite is supplie...",""],
["./adjustment.htm","Adjustment window","﻿Adjustment window The adjustment window The adjustment window offers controls to change overall properties within the selected flame. From here y...",""],
["./autosave.htm","Autosave options","﻿Autosave options File name The path to the batch file where the automatically saved flames should be stored in. Save frequency The interval in mi...",""],
["./coloring.htm","Coloring","﻿Coloring Contrary to common belief, coloring fractal flame does not work like in graphic applications like GIMP or Photoshop. It is rather the se...",""],
["./comments.htm","Comments","﻿Comments Comments can assist you and others while reading the script. There are three types of comments: • Single-line comments (starting with \"/...",""],
["./conditions_and_loops.htm","Conditions and Loops","﻿Conditions and Loops Apophysis script supports conditional execution of code through branching statements: if J &#60;&#62; 0 then Result := I/J; if J = 0...",""],
["./display.htm","Display options","﻿Display options Rendering Specifies rendering options for the main preview. Preview density Specifies point densities for the mini previews. Exte...",""],
["./editor.htm","Editor window","﻿Editor window The editor window The editor window is your central place to design fractal flames. It offers full control over the appearance of y...",""],
["./editor2.htm","Editor options","﻿Editor options Use transform color Displays the triangles in their individual transform colors (which you can specify in the corresponding color ...",""],
["./editor_window.htm","Editor window","﻿Editor window The editor window The editor window is your central place to design fractal flames. It offers full control over the appearance of y...",""],
["./flames.htm","Fractal Flames","﻿Fractal Flames Jump to: Transforms - Variations - Coloring - Xaos Transforms Transforms are probably the most important elements of fractal flame...",""],
["./flame_interface.htm","Flame interface","﻿Flame interface Properties Flame.Name The name of the flame in memory but not on the batch listing. Flame.SampleDensity The sample density (\"qual...",""],
["./general.htm","General options","﻿General options Multithreading You can specify the amount of threads Apophysis uses during rendering both - previews and final images - here. You...",""],
["./general_interface.htm","Pre-defined procedures and constants","﻿Pre-defined procedures and constants General procedures and functions Preview; Opens the preview window and displays the current flame. print( &#39;s...",""],
["./gradient.htm","Gradient options","﻿Gradient options On random flame You can set which gradient should be used in randomly generated flames here. Smooth palette Specifies options fo...",""],
["./home.htm","Home","﻿Apophysis 7X Apophysis 7X is an improved version of the famous fractal flame editor Apophysis which is used by artists all over the world to gene...",""],
["./identifiers.htm","Identifiers","﻿Identifiers Identifier names in scripts (variable names, function and procedure names, ...) should begin with a letter (a..z or A..Z) or an under...",""],
["./language.htm","Language","﻿Language Jump to: Identifiers - Literals and Operators - Conditions and Loops - Procedures and Functions - Comments Identifiers Identifier names ...",""],
["./literals_and_operators.htm","Literals and Operators","﻿Literals and Operators There is a number of operators in the script language: • Basic operations (addition, subtraction, multiplication, division...",""],
["./main_window.htm","Main window","﻿Main window The main window of Apophysis 7X.13 The main window is the first thing you will see when Apophysis starts. It consists of various area...",""],
["./menu.htm","Main menu","﻿Main menu Jump to: File - Edit - View - Flame - Variation - Script - Options - Help File New... Depending on your settings, this entry either cre...",""],
["./mutation.htm","Mutation window","﻿Mutation window The mutation window The mutation window offers an easy way to change the appearance of your flame. This feature is a remainder of...",""],
["./operations.htm","Operations","﻿Operations The transform operations are no members of the flame interface - which means you don&#39;t prepend \"Transform.\" to the procedure name. Add...",""],
["./operations2.htm","Operations","﻿Operations The flame operations are no members of the flame interface - which means you don&#39;t prepend \"Flame.\" to the procedure name. StoreFlame(...",""],
["./options.htm","Options window","﻿Options window Jump to: General - Editor - Display - Random - Variations - Gradient - UPR - Paths - Autosave General options Multithreading You c...",""],
["./paths.htm","Search paths","﻿Search paths Default parameter file Specifies the batch file which should be loaded after Apophysis started. If you leave this field empty, a ran...",""],
["./procedures_and_functions.htm","Procedures and Functions","﻿Procedures and Functions Apophysis script supports the definition of own sub-programs with either no return value (procedures) or with a return v...",""],
["./properties.htm","Properties","﻿Properties Flame.Name The name of the flame in memory but not on the batch listing. Flame.SampleDensity The sample density (\"quality\") of the fla...",""],
["./properties2.htm","Properties","﻿Properties Transform.A..Transform.F The values within the selected transformation matrix: A = Xx, B = Xy, C = Yx, D = Yy, E = Ox, F = Oy Default ...",""],
["./random.htm","Randomization options","﻿Randomization options Number of transforms Specifies the range of the amount of transforms when generating a random batch. Mutation transforms Sp...",""],
["./rendering.htm","Rendering window","﻿Rendering window The render window The render window offers you a vast amount of options to turn your flame into an image file. The \"Output\" tab ...",""],
["./scripting.htm","Scripting","﻿Apophysis Scripting System Jump to: Language - Pre-defined procedures/constants - Flame interface - Transform interface Language Jump to: Identif...",""],
["./toolbar.htm","Main toolbar","﻿Main toolbar New Depending on your settings, this entry either creates a blank flame or opens a window where you can select a basic flame style t...",""],
["./toolbar2.htm","Editor toolbar","﻿Editor toolbar Erase flame Replaces the currently selected flame with a blank flame. Add transform Adds a new transform. Duplicate transform Dupl...",""],
["./transforms.htm","Transforms","﻿Transforms Transforms are probably the most important elements of fractal flames. Each flame consists of a set of transforms where each transform...",""],
["./transform_interface.htm","Transform interface","﻿Transform interface Properties Transform.A..Transform.F The values within the selected transformation matrix: A = Xx, B = Xy, C = Yx, D = Yy, E =...",""],
["./upr.htm","UPR options","﻿UPR options This tab offers options to export Apophysis flames into UltraFractal parameters. It is for advanced users and you should consult the ...",""],
["./variations.htm","Variations","﻿Variations Variations in Apophysis are essential for the vast amount of different types of fractal flames. There are many variations built into A...",""],
["./variations2.htm","Variation selection","﻿Variation selection You can select the transforms which are allowed to be applied when generating a random batch here. By default, only linear is...",""],
["./windows.htm","Windows","﻿Apophysis Windows Jump to: Main window - Editor window - Adjustment window - Rendering window - Mutation window - Options window Main window The ...",""],
["./xaos.htm","Xaos","﻿Xaos Xaos is a relatively new feature in Apophysis. The artificial word \"Xaos\" abstracts either the term \"controlled chaos\" or \"weight modifier\" ...",""]];
