//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18010
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xyrus.PluginCodeGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xyrus.PluginCodeGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        ///    Apophysis Plugin: &lt;%NAME%&gt;
        ///
        ///    This program is free software; you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation; either version 2 of the License, or
        ///    (at your option) any later version.
        ///
        ///    This program is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///    GNU  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CppFile {
            get {
                return ResourceManager.GetString("CppFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LIBRARY
        ///EXPORTS
        ///	PluginVarPrepare
        ///	PluginVarCalc
        ///	PluginVarResetVariable
        ///	PluginVarGetVariableNameAt
        ///	PluginVarGetVariable
        ///	PluginVarSetVariable
        ///	PluginVarGetNrVariables
        ///	PluginVarGetName
        ///	PluginVarGetArchitecture
        ///	PluginVarCreate
        ///	PluginVarDestroy
        ///	PluginVarInit
        ///	PluginVarInit3D
        ///	PluginVarInitDC ähnelt.
        /// </summary>
        internal static string DefFile {
            get {
                return ResourceManager.GetString("DefFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR: {0} ähnelt.
        /// </summary>
        internal static string ErrorFormatString {
            get {
                return ResourceManager.GetString("ErrorFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed. ähnelt.
        /// </summary>
        internal static string FailedString {
            get {
                return ResourceManager.GetString("FailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #pragma once
        ///
        ///#ifdef APO_NOVARIABLES
        ///	#include &quot;plugin_novar.h&quot;
        ///#else
        ///	#include &quot;plugin.h&quot;
        ///#endif ähnelt.
        /// </summary>
        internal static string HeaderFile {
            get {
                return ResourceManager.GetString("HeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #pragma once
        ///
        ///#include &lt;stdlib.h&gt;
        ///#include &lt;malloc.h&gt;
        ///#include &lt;math.h&gt;
        ///#include &lt;time.h&gt;
        ///#include &lt;string.h&gt;
        ///#include &lt;limits.h&gt;
        ///#include &lt;float.h&gt;
        ///
        ///#ifndef TRUE
        ///	#define TRUE (1)
        ///	#define FALSE (0)
        ///#endif
        ///
        ///#define EPS			1.0e-20
        ///#define M_2PI       6.283185307179586476925286766559
        ///#define M_3PI_4     2.3561944901923449288469825374596
        ///#define M_SQRT3     1.7320508075688772935274463415059
        ///#define M_SQRT3_2   0.86602540378443864676372317075249
        ///#define M_SQRT5     2.236067977499789696409173 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HeaderFileNoVar {
            get {
                return ResourceManager.GetString("HeaderFileNoVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #pragma once
        ///
        ///#include &lt;stdlib.h&gt;
        ///#include &lt;malloc.h&gt;
        ///#include &lt;math.h&gt;
        ///#include &lt;time.h&gt;
        ///#include &lt;string.h&gt;
        ///#include &lt;limits.h&gt;
        ///#include &lt;float.h&gt;
        ///
        ///#ifndef TRUE
        ///	#define TRUE (1)
        ///	#define FALSE (0)
        ///#endif
        ///
        ///#define EPS			1.0e-20
        ///#define M_2PI       6.283185307179586476925286766559
        ///#define M_3PI_4     2.3561944901923449288469825374596
        ///#define M_SQRT3     1.7320508075688772935274463415059
        ///#define M_SQRT3_2   0.86602540378443864676372317075249
        ///#define M_SQRT5     2.236067977499789696409173 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HeaderFileVar {
            get {
                return ResourceManager.GetString("HeaderFileVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project DefaultTargets=&quot;Build&quot; ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ItemGroup Label=&quot;ProjectConfigurations&quot;&gt;
        ///    &lt;ProjectConfiguration Include=&quot;Debug|Win32&quot;&gt;
        ///      &lt;Configuration&gt;Debug&lt;/Configuration&gt;
        ///      &lt;Platform&gt;Win32&lt;/Platform&gt;
        ///    &lt;/ProjectConfiguration&gt;
        ///    &lt;ProjectConfiguration Include=&quot;Debug|x64&quot;&gt;
        ///      &lt;Configuration&gt;Debug&lt;/Configuration&gt;
        ///      &lt;Platform&gt;x64&lt;/Platform&gt;
        ///    &lt;/ProjectConfiguration&gt;
        ///     [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the new project name:  ähnelt.
        /// </summary>
        internal static string PromptString {
            get {
                return ResourceManager.GetString("PromptString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successful. ähnelt.
        /// </summary>
        internal static string SuccessfulString {
            get {
                return ResourceManager.GetString("SuccessfulString", resourceCulture);
            }
        }
    }
}
